// <auto-generated />
using System;
using Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hogar"
                        });
                });

            modelBuilder.Entity("Domain.InventoryEntity", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Inventories", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("46f3f79d-0488-4f61-abcd-517cce578cd4"),
                            WarehouseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("d0151aab-c32e-4b50-b629-e380f50342c8"),
                            WarehouseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("20624587-9688-4842-801e-5a98219c3fb6"),
                            WarehouseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("a1779efe-cdb4-4e67-9dd0-5da791841132"),
                            WarehouseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("39a0bd15-b635-422a-b1bf-54dc66cb1581"),
                            WarehouseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("3fef1b0e-1fbf-4f77-ae32-e5828cdd7fec"),
                            WarehouseId = new Guid("11111111-1111-1111-1111-111111111111"),
                            StockQuantity = 100
                        },
                        new
                        {
                            ProductId = new Guid("46f3f79d-0488-4f61-abcd-517cce578cd4"),
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("d0151aab-c32e-4b50-b629-e380f50342c8"),
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("20624587-9688-4842-801e-5a98219c3fb6"),
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("a1779efe-cdb4-4e67-9dd0-5da791841132"),
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("39a0bd15-b635-422a-b1bf-54dc66cb1581"),
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = new Guid("3fef1b0e-1fbf-4f77-ae32-e5828cdd7fec"),
                            WarehouseId = new Guid("22222222-2222-2222-2222-222222222222"),
                            StockQuantity = 50
                        });
                });

            modelBuilder.Entity("Domain.OrderDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuantityOrdered")
                        .HasColumnType("int");

                    b.Property<int>("QuantityScanned")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails", (string)null);
                });

            modelBuilder.Entity("Domain.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Folio")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Folio")
                        .IsUnique()
                        .HasFilter("[Folio] IS NOT NULL");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Domain.OrderStatusHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("OrderStatusHistory", (string)null);
                });

            modelBuilder.Entity("Domain.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreateAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Barcode")
                        .IsUnique();

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("46f3f79d-0488-4f61-abcd-517cce578cd4"),
                            Barcode = "123456789",
                            Name = "Asus Vivobook",
                            Price = 25.50m,
                            ProductDescription = "The ASUS Vivobook is a versatile",
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = new Guid("d0151aab-c32e-4b50-b629-e380f50342c8"),
                            Barcode = "163062",
                            Name = "Escritorio de baal con 3 cajones color nogal",
                            Price = 25.50m,
                            ProductDescription = "Modelo Baal walnut b",
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = new Guid("20624587-9688-4842-801e-5a98219c3fb6"),
                            Barcode = "198866",
                            Name = "Tarja eb de 1 tinas",
                            Price = 25.50m,
                            ProductDescription = "Modelo Eb onen33229-1012hf",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = new Guid("a1779efe-cdb4-4e67-9dd0-5da791841132"),
                            Barcode = "198865",
                            Name = "Tarja eb de 2 tinas",
                            Price = 25.50m,
                            ProductDescription = "Modelo Eb onen33229-1012hd",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = new Guid("39a0bd15-b635-422a-b1bf-54dc66cb1581"),
                            Barcode = "198867",
                            Name = "Tarja eb de 3 tinas",
                            Price = 25.50m,
                            ProductDescription = "Modelo Eb onen33229-1012ht",
                            SubCategoryId = 4
                        },
                        new
                        {
                            Id = new Guid("3fef1b0e-1fbf-4f77-ae32-e5828cdd7fec"),
                            Barcode = "1234563",
                            Name = "Xiaomi POCO F7 Ultra",
                            Price = 25.50m,
                            ProductDescription = "Fruta seleccionada de alta calidad",
                            SubCategoryId = 2
                        });
                });

            modelBuilder.Entity("Domain.SubCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Laptops"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Celulares"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Muebles"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Cocina"
                        });
                });

            modelBuilder.Entity("Domain.WarehouseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Bodega Central"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Bodega Secundaria"
                        });
                });

            modelBuilder.Entity("Domain.InventoryEntity", b =>
                {
                    b.HasOne("Domain.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.WarehouseEntity", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Domain.OrderDetailEntity", b =>
                {
                    b.HasOne("Domain.OrderEntity", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.ProductEntity", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.ProductEntity", b =>
                {
                    b.HasOne("Domain.SubCategoryEntity", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("Domain.SubCategoryEntity", b =>
                {
                    b.HasOne("Domain.CategoryEntity", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.CategoryEntity", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("Domain.OrderEntity", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Domain.SubCategoryEntity", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
